// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTNnIDdmplYoqab-nTfI_ORD_j8p_Vvc',
    appId: '1:977561167845:web:7e1e5201fbf509c27c710c',
    messagingSenderId: '977561167845',
    projectId: 'todo-34d8c',
    authDomain: 'todo-34d8c.firebaseapp.com',
    storageBucket: 'todo-34d8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrc9KByuWds0nKDBW3__gQBdBX8r7PR9g',
    appId: '1:977561167845:android:df3312d8f75812f57c710c',
    messagingSenderId: '977561167845',
    projectId: 'todo-34d8c',
    storageBucket: 'todo-34d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Gjrnd3bZHR7-4JBrJCkjd1SyQj4e3U4',
    appId: '1:977561167845:ios:ece24abc67f8a4957c710c',
    messagingSenderId: '977561167845',
    projectId: 'todo-34d8c',
    storageBucket: 'todo-34d8c.appspot.com',
    iosBundleId: 'com.example.todoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Gjrnd3bZHR7-4JBrJCkjd1SyQj4e3U4',
    appId: '1:977561167845:ios:ece24abc67f8a4957c710c',
    messagingSenderId: '977561167845',
    projectId: 'todo-34d8c',
    storageBucket: 'todo-34d8c.appspot.com',
    iosBundleId: 'com.example.todoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzTNnIDdmplYoqab-nTfI_ORD_j8p_Vvc',
    appId: '1:977561167845:web:73960bf2be6f2f957c710c',
    messagingSenderId: '977561167845',
    projectId: 'todo-34d8c',
    authDomain: 'todo-34d8c.firebaseapp.com',
    storageBucket: 'todo-34d8c.appspot.com',
  );
}
